# -*- coding: utf-8 -*- 
"""2_3_4_Actividad_Pluma_de_Agua_Algoritmo_GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/justorfc/Programacion_2026_1/blob/main/2_3_4_Actividad_Pluma_de_Agua_Algoritmo_GitHub.ipynb

# Actividad de Programación con Python  
## **Historia, ciencia y programación: la “pluma de agua”**

> **Relato de partida**  
> **¿Por qué los costeños le decimos “pluma” a la llave del agua?**  
>  
> En el Caribe colombiano, abrir la “pluma” no es solo una acción cotidiana: es una expresión cargada de historia, técnica y cultura. Aunque algunos se sorprendan o incluso se burlen del término, lo cierto es que decir “pluma” en vez de “llave” no es un error, sino una herencia viva que conecta nuestro lenguaje con siglos de evolución hidráulica.  
>  
> Mucho antes de que existieran los grifos modernos, el agua se distribuía mediante sistemas regulados con precisión. En España, por ejemplo, se usaba la **“pluma de agua”** como unidad de medida para calcular el caudal que se entregaba a cada hogar. Aproximadamente, una pluma equivalía a **0.025 litros por segundo**. En algunos lugares, ese flujo se regulaba mediante orificios calibrados y dispositivos llamados **plumeros**, que permitían controlar la salida del agua.  
>  
> Durante la época colonial, muchas de estas prácticas técnicas cruzaron el Atlántico y llegaron a ciudades como Cartagena, Barranquilla y Santa Marta. Con el tiempo, el término “pluma” dejó de ser solamente técnico y pasó al habla cotidiana como sinónimo de la llave del agua.  
>  
> Así, una palabra del uso diario conserva una memoria histórica, tecnológica y cultural.  
>  
> ---
>  
> **Idea central para esta actividad:**  
> A partir de este relato, construiremos un problema de programación donde una magnitud histórica y física, el **caudal de una pluma de agua**, se represente mediante variables, operaciones y estructuras básicas de Python.

## 1. Propósito de la actividad

Al finalizar esta actividad, el estudiante debe ser capaz de:

- interpretar un contexto histórico y científico como un problema computacional;
- identificar entradas, procesos y salidas;
- diseñar un algoritmo antes de programar;
- implementar el programa en Python;
- publicar el trabajo en GitHub;
- ampliar la documentación del código;
- clonar el repositorio al disco local usando Git.

> **Importante:**  
> En este notebook **no se entrega la solución completa**.  
> Aquí se presenta el **planteamiento**, la **estructura del problema** y el **algoritmo guía** para que cada estudiante construya el código.

## 2. Situación problema

Un hogar recibe una cierta cantidad de **plumas de agua**.  
Se sabe que:

- **1 pluma = 0.025 litros por segundo**

Con esta información, el estudiante debe construir un programa que permita calcular:

1. el caudal total en litros por segundo;
2. el consumo diario en litros;
3. el consumo mensual en litros (suponiendo 30 días);
4. una clasificación del consumo:
   - **Bajo**: menos de 1000 litros por día
   - **Medio**: entre 1000 y 3000 litros por día
   - **Alto**: más de 3000 litros por día

---

## 3. Análisis del problema

### 3.1 Entrada del sistema
El programa debe recibir:

- número de plumas asignadas al hogar.

### 3.2 Proceso
El programa debe:

- convertir el número de plumas en caudal total;
- transformar el caudal a consumo diario;
- transformar el consumo diario a consumo mensual;
- clasificar el nivel de consumo.

### 3.3 Salida
El programa debe mostrar:

- caudal total;
- consumo diario;
- consumo mensual;
- clasificación del consumo.

## 4. Variables y constantes sugeridas

El estudiante puede trabajar con variables como las siguientes:

- `plumas`
- `caudal_pluma`
- `caudal_total`
- `segundos_dia`
- `consumo_diario`
- `consumo_mensual`
- `nivel_consumo`

> Puede cambiar los nombres, pero deben ser claros y significativos.

## 5. Algoritmo propuesto

Antes de programar, escriba el algoritmo en lenguaje natural o seudocódigo.

### Algoritmo en lenguaje natural

1. Solicitar al usuario el número de plumas de agua.
2. Definir el valor de una pluma en litros por segundo.
3. Definir la cantidad de segundos que tiene un día.
4. Calcular el caudal total.
5. Calcular el consumo diario.
6. Calcular el consumo mensual.
7. Determinar si el consumo es bajo, medio o alto.
8. Mostrar los resultados de manera clara.

### Seudocódigo guía

```text
Inicio
    Leer número de plumas
    Definir caudal de una pluma
    Definir segundos por día

    Calcular caudal total
    Calcular consumo diario
    Calcular consumo mensual

    Si consumo diario es menor que 1000
        nivel = "Bajo"
    Si no, si consumo diario está entre 1000 y 3000
        nivel = "Medio"
    En otro caso
        nivel = "Alto"

    Mostrar caudal total
    Mostrar consumo diario
    Mostrar consumo mensual
    Mostrar nivel
Fin
```

## 6. Espacio para que el estudiante construya la solución

### Instrucciones
Complete el siguiente bloque de código a partir del algoritmo anterior.

- No copie una solución terminada sin comprenderla.
- Escriba comentarios propios.
- Use nombres de variables comprensibles.
- Verifique que los resultados tengan sentido físico.
"""

# ==========================================================
# ACTIVIDAD: MODELAR LA "PLUMA DE AGUA" CON PYTHON
# ==========================================================

# 1. Solicitar al usuario el número de plumas
# Escriba aquí su código

# 2. Definir constantes del problema
# Escriba aquí su código


# 3. Calcular el caudal total
# Escriba aquí su código


# 4. Calcular el consumo diario
# Escriba aquí su código


# 5. Calcular el consumo mensual
# Escriba aquí su código


# 6. Clasificar el consumo
# Escriba aquí su código


# 7. Mostrar resultados
# Escriba aquí su código

"""## 7. Verificación conceptual

Antes de dar por terminado el programa, responda en comentarios o en una celda Markdown:

1. ¿Qué representa físicamente la variable principal del problema?
2. ¿Por qué este ejercicio conecta historia, cultura e ingeniería?
3. ¿Qué operaciones aritméticas fueron necesarias?
4. ¿Qué estructura condicional utilizó y por qué?
5. ¿Cómo interpretaría el resultado en un contexto real?

## 8. Extensión opcional

Si desea profundizar, puede ampliar el programa para que también permita:

- calcular el consumo semanal;
- comparar el consumo de varios hogares;
- estimar el costo del agua si se conoce una tarifa por litro o por metro cúbico;
- convertir litros a metros cúbicos;
- presentar los resultados en forma tabular.

> Estas extensiones no reemplazan la solución base; son una ampliación.

## 9. Documentación del código con apoyo de IA

Después de construir y probar su programa:

1. Copie su código en ChatGPT.
2. Solicite una **explicación técnica en Markdown** del código.
3. Pida además:
   - descripción de la función del programa;
   - explicación de cada sección;
   - explicación de variables, entradas, procesos y salidas;
   - observaciones sobre claridad y buenas prácticas.
4. Mejore su código con base en esa retroalimentación.
5. Actualice su repositorio en GitHub con la versión mejorada y documentada.

### Prompt sugerido para documentar el código

```text
Actúa como docente universitario experto en programación con Python.

Te voy a compartir un código en Python.
Necesito que expliques el código en formato Markdown de manera clara, técnica y ordenada.

Incluye:
1. propósito general del programa;
2. explicación de entradas, procesos y salidas;
3. descripción de cada variable importante;
4. explicación de las estructuras usadas;
5. observaciones sobre claridad, estilo y posibles mejoras;
6. una versión comentada del código, sin cambiar su lógica.

Aquí está mi código:
[PEGAR AQUÍ EL CÓDIGO]
```

## 10. Trabajo con GitHub

Una vez terminado el programa:

1. Cree un repositorio en GitHub.
2. Suba el notebook o el archivo `.py`.
3. Haga un primer commit.
4. Después de ampliar la documentación del código, haga un segundo commit.
5. Copie la URL del repositorio y consérvela para la entrega.

### Ejemplo de estructura del repositorio

```text
actividad-pluma-agua/
│
├── README.md
├── pluma_agua.py
└── Actividad_Pluma_de_Agua_Algoritmo_GitHub.ipynb
```

## 11. Comandos Git sugeridos

> **Nota:** estos comandos deben ejecutarse en la terminal, Git Bash o PowerShell.

### 11.1 Inicializar el repositorio local

```bash
git init
git add .
git commit -m "Versión inicial de la actividad pluma de agua"
```

### 11.2 Conectar con GitHub

```bash
git branch -M main
git remote add origin URL_DEL_REPOSITORIO
git push -u origin main
```

### 11.3 Subir una segunda versión con mejor documentación

```bash
git add .
git commit -m "Se mejora documentación y comentarios del código"
git push
```

## 12. Clonar el repositorio en el disco local C:

Una vez que el repositorio esté en GitHub, copie su URL y ejecute:

```bash
cd /c
git clone URL_DEL_REPOSITORIO
```

Si está usando PowerShell en Windows, también puede hacerlo así:

```powershell
cd C:\
git clone URL_DEL_REPOSITORIO
```

### Ejemplo esperado

Si su repositorio se llama:

```text
https://github.com/usuario/actividad-pluma-agua.git
```

entonces el comando sería:

```bash
git clone https://github.com/usuario/actividad-pluma-agua.git
```

Con esto se creará una carpeta del proyecto dentro de `C:\`.

## 13. Evidencia de entrega sugerida

El estudiante debe entregar:

- el enlace del repositorio en GitHub;
- el notebook o archivo `.py` funcional;
- una versión documentada del código;
- evidencia de que el repositorio fue clonado en el equipo local.

### Evidencia mínima recomendada
- captura del repositorio en GitHub;
- captura de los commits;
- captura del comando `git clone` ejecutado correctamente.

## 14. Reflexión final

Este ejercicio no trata solamente de programar.  
También muestra cómo una palabra cotidiana del Caribe colombiano puede llevarnos a:

- la historia de la hidráulica;
- la representación computacional de una magnitud física;
- el diseño de algoritmos;
- el uso responsable de herramientas como GitHub y ChatGPT en el trabajo académico.

> La programación también puede nacer de la memoria cultural y del contexto local.

## 15. Espacio para notas del estudiante

Escriba aquí una breve reflexión personal:

- ¿Qué aprendió?
- ¿Qué parte le resultó más difícil?
- ¿Qué mejoró cuando documentó el código?
- ¿Qué importancia tiene publicar y versionar su trabajo?
"""
